# Lab 136 知识点总结：
# - aws_iam_policy_document 是 AWS Provider 的 data source，用 Terraform HCL 结构渲染 IAM JSON policy document。
# - 它不创建 IAM 对象，也不查询 CloudWatch Logs；真正调用 IAM API 的是消费 `.json` 的 aws_iam_policy resource。
# - statement block 使用复数参数 actions/resources，对应最终 JSON 中的 Action/Resource。
# - actions/resources 输入即使是 list，只有一个元素时，Provider 生成的 JSON 可能规范化为单个字符串；二者 IAM 语义等价。
# - effect 可省略且默认是 Allow；本 Lab 故意在第一条 statement 省略它，再从生成 JSON 中观察默认值。
# - 生成结果通过 `.json` 取得格式化 JSON 字符串；`.minified_json` 是语义相同的压缩形式。
# - data.aws_iam_policy_document.read_logs.json 被 resource 引用后，会建立 Data Source → Policy 的依赖关系。
# - DescribeLogGroups 不支持资源级授权，因此 Resource 必须是 "*"；GetLogEvents 支持 log-stream ARN。
# - Terraform interpolation 先把 var.aws_region 写入 ARN，再由 policy document data source 生成 JSON。
# - data source 能检查 HCL block/参数结构并保证 JSON 格式，但不会验证 Action 拼写或真实 AWS 的最终授权效果。
# - jsondecode() 可把生成 JSON 转回 Terraform value，适合测试 Statement 的实际语义，而不是比较空格和缩进。
# - LocalStack 能验证 IAM Policy 创建与销毁闭环，但不能替代 IAM Access Analyzer、SCP 或 permission boundary 验证。
#
# 请依次完成 TODO 1～3；每个 TODO 都有可直接取消注释的完整答案级 Hint。

locals {
  log_stream_arn = "arn:aws:logs:${var.aws_region}:*:log-group:/aws/lambda/tf-pro-lab-136:log-stream:*"
}

# TODO 1：使用 aws_iam_policy_document 生成两条 CloudWatch Logs 权限 statement。
# 第一条故意省略 effect，观察生成 JSON 是否自动得到 Allow。
# 答案级 Hint：完整答案如下，取消注释即可：
#
# data "aws_iam_policy_document" "read_logs" {
#   statement {
#     sid = "DescribeLogGroups"
#
#     actions   = ["logs:DescribeLogGroups"]
#     resources = ["*"]
#   }
#
#   statement {
#     sid    = "ReadLogStream"
#     effect = "Allow"
#
#     actions   = ["logs:GetLogEvents"]
#     resources = [local.log_stream_arn]
#   }
# }

# TODO 2：创建 customer managed policy，并把 data source 生成的 `.json` 传给 policy 参数。
# 答案级 Hint：完整答案如下，取消注释即可：
#
# resource "aws_iam_policy" "read_logs" {
#   name        = "tf-pro-lab-136-read-logs"
#   description = "Read selected CloudWatch Logs metadata and events."
#   policy      = data.aws_iam_policy_document.read_logs.json
#
#   tags = {
#     Course = "terraform-pro"
#     Lab    = "136"
#   }
# }

# TODO 3：同时输出资源身份和解码后的策略语义。
# jsondecode 避免测试依赖 JSON 的空格、换行或 key 顺序。
# 答案级 Hint：完整答案如下，取消注释即可：
#
# output "policy_summary" {
#   description = "Identity and structural summary of the generated IAM policy."
#   value = {
#     name            = aws_iam_policy.read_logs.name
#     arn             = aws_iam_policy.read_logs.arn
#     version         = jsondecode(data.aws_iam_policy_document.read_logs.json).Version
#     statement_count = length(jsondecode(data.aws_iam_policy_document.read_logs.json).Statement)
#   }
# }
#
# output "policy_document" {
#   description = "Generated policy decoded back into a Terraform value for semantic inspection."
#   value       = jsondecode(data.aws_iam_policy_document.read_logs.json)
# }
#
# output "policy_json" {
#   description = "Formatted JSON string generated by aws_iam_policy_document."
#   value       = data.aws_iam_policy_document.read_logs.json
# }
