terraform {
  required_version = ">= 1.5.0"
}

locals {
  # TODO 1: Set the simulated EC2 instance name.
  # Hint: use "training-web-01".
  instance_name = "replace-me"

  # TODO 2: Set the simulated AMI ID.
  # Hint: use "ami-0123456789abcdef0".
  ami_id = "ami-00000000000000000"

  # TODO 3: Set the instance type.
  # Hint: use "t3.micro".
  instance_type = "t2.nano"

  # TODO 4: Disable public IP assignment.
  # Hint: set this to false.
  enable_public_ip = true

  # TODO 5: Build the standard tags map.
  # Hint: include Environment, Owner, and ManagedBy.
  tags = {}
}

module "ec2_instance" {
  source = "./modules/ec2_instance_blueprint"

  name             = local.instance_name
  ami_id           = local.ami_id
  instance_type    = local.instance_type
  enable_public_ip = local.enable_public_ip
  tags             = local.tags
}

resource "terraform_data" "lesson" {
  input = {
    topic         = "module call and ec2 blueprint"
    module_source = "./modules/ec2_instance_blueprint"
  }
}

output "ec2_instance_config" {
  description = "EC2 instance blueprint generated by the child module."

  # TODO 6: Read the child module output instead of this placeholder object.
  # Hint: use module.ec2_instance.instance_config.
  value = {
    name             = local.instance_name
    ami_id           = local.ami_id
    instance_type    = local.instance_type
    enable_public_ip = local.enable_public_ip
    tags             = local.tags
    generated_by     = "root-placeholder"
  }
}

output "lesson_topic" {
  description = "Current lab topic."
  value       = terraform_data.lesson.input.topic
}
