terraform {
  required_version = ">= 1.5.0"
}

locals {
  instance_name = "training-web-01"

  ami_id = "ami-0123456789abcdef0"

  instance_type = "t3.micro"

  enable_public_ip = false

  tags = {
    Environment = "dev"
    Owner       = "platform"
    ManagedBy   = "terraform"
  }
}

module "ec2_instance" {
  source = "./modules/ec2_instance_blueprint"

  name             = local.instance_name
  ami_id           = local.ami_id
  instance_type    = local.instance_type
  enable_public_ip = local.enable_public_ip
  tags             = local.tags
}

resource "terraform_data" "lesson" {
  input = {
    topic         = "module call and ec2 blueprint"
    module_source = "./modules/ec2_instance_blueprint"
  }
}

output "ec2_instance_config" {
  description = "EC2 instance blueprint generated by the child module."
  value       = module.ec2_instance.instance_config
}

output "lesson_topic" {
  description = "Current lab topic."
  value       = terraform_data.lesson.input.topic
}
