terraform {
  required_version = ">= 1.5.0"
}

module "team_one" {
  source = "./modules/flexible_instance"

  name               = "team-one-api"
  environment        = "dev"
  instance_type      = "t2.micro"
  enable_hibernation = false
  tags = {
    team        = "platform"
    cost_center = "cc-100"
  }
}

module "team_two" {
  source = "./modules/flexible_instance"

  name               = "team-two-worker"
  environment        = "prod"
  instance_type      = "m5.large"
  enable_hibernation = true
  tags = {
    team        = "payments"
    cost_center = "cc-200"
  }
}

resource "terraform_data" "lesson" {
  input = {
    topic     = "module variables and avoiding hardcoding"
    team_one  = module.team_one.profile
    team_two  = module.team_two.profile
    lesson_no = 93
  }
}

output "team_one_profile" {
  description = "Profile generated by the flexible_instance module for team one."
  value       = module.team_one.profile
}

output "team_two_profile" {
  description = "Profile generated by the flexible_instance module for team two."
  value       = module.team_two.profile
}

output "instance_types_by_team" {
  description = "Instance type selected by each module caller."
  value = {
    team_one = module.team_one.profile.instance_type
    team_two = module.team_two.profile.instance_type
  }
}

output "module_labels" {
  description = "Labels generated inside the child module."
  value = [
    module.team_one.profile.label,
    module.team_two.profile.label
  ]
}
