output "instance_record" {
  description = "Standardized mock EC2 instance record."
  value       = local.instance_record
}

output "tags" {
  description = "Merged tags generated by the local EC2 module."
  value       = local.standard_tags
}
