terraform {
  required_version = ">= 1.5.0"
}

locals {
  users = ["alice", "bob", "john"]

  upper_users = [for user in local.users : upper(user)]

  indexed_users = [for index, user in local.users : "${index}:${user}"]

  short_users = [for user in local.users : user if length(user) <= 4]

  service_ports = {
    api    = 8080
    worker = 9000
    web    = 8081
  }

  service_port_labels = [for name, port in local.service_ports : "${name}:${port}"]

  user_lookup = { for user in local.users : user => upper(user) }

  public_service_ports = { for name, port in local.service_ports : name => port if port < 9000 }
}

resource "terraform_data" "lesson" {
  input = {
    topic = "for expressions basics"
    users = local.users
  }
}

output "users" {
  description = "Input list of user names."
  value       = local.users
}

output "upper_users" {
  description = "User names converted to uppercase with a for expression."
  value       = local.upper_users
}

output "indexed_users" {
  description = "Index and user name labels generated with a for expression."
  value       = local.indexed_users
}

output "short_users" {
  description = "Filtered user names with four or fewer characters."
  value       = local.short_users
}

output "service_port_labels" {
  description = "Labels generated by iterating over a map."
  value       = local.service_port_labels
}

output "user_lookup" {
  description = "Map generated from the user list."
  value       = local.user_lookup
}

output "public_service_ports" {
  description = "Filtered service port map generated with a for expression."
  value       = local.public_service_ports
}
