terraform {
  required_version = ">= 1.5.0"
}

locals {
  users = ["alice", "bob", "john"]

  # TODO 1: Convert every user name to uppercase.
  # Hint: use [for user in local.users : upper(user)].
  upper_users = []

  # TODO 2: Build "index:name" labels from the users list.
  # Hint: use [for index, user in local.users : "${index}:${user}"].
  indexed_users = []

  # TODO 3: Keep only user names with four or fewer characters.
  # Hint: use [for user in local.users : user if length(user) <= 4].
  short_users = []

  service_ports = {
    api    = 8080
    worker = 9000
    web    = 8081
  }

  # TODO 4: Convert the service port map into "service:port" labels.
  # Hint: use [for name, port in local.service_ports : "${name}:${port}"].
  service_port_labels = []

  # TODO 5: Convert the users list into a map keyed by user name.
  # Hint: use { for user in local.users : user => upper(user) }.
  user_lookup = {}

  # TODO 6: Filter the service port map to keep only ports below 9000.
  # Hint: use { for name, port in local.service_ports : name => port if port < 9000 }.
  public_service_ports = {}
}

resource "terraform_data" "lesson" {
  input = {
    topic = "for expressions basics"
    users = local.users
  }
}

output "users" {
  description = "Input list of user names."
  value       = local.users
}

output "upper_users" {
  description = "User names converted to uppercase with a for expression."
  value       = local.upper_users
}

output "indexed_users" {
  description = "Index and user name labels generated with a for expression."
  value       = local.indexed_users
}

output "short_users" {
  description = "Filtered user names with four or fewer characters."
  value       = local.short_users
}

output "service_port_labels" {
  description = "Labels generated by iterating over a map."
  value       = local.service_port_labels
}

output "user_lookup" {
  description = "Map generated from the user list."
  value       = local.user_lookup
}

output "public_service_ports" {
  description = "Filtered service port map generated with a for expression."
  value       = local.public_service_ports
}
