run "for_expressions_are_correct" {
  command = plan

  assert {
    condition     = output.users == ["alice", "bob", "john"]
    error_message = "users must contain alice, bob, and john."
  }

  assert {
    condition     = output.upper_users == ["ALICE", "BOB", "JOHN"]
    error_message = "upper_users must convert every user name to uppercase."
  }

  assert {
    condition     = output.indexed_users == ["0:alice", "1:bob", "2:john"]
    error_message = "indexed_users must include each user's zero-based index."
  }

  assert {
    condition     = output.short_users == ["bob", "john"]
    error_message = "short_users must keep only names with four or fewer characters."
  }

  assert {
    condition     = output.service_port_labels == ["api:8080", "web:8081", "worker:9000"]
    error_message = "service_port_labels must be generated by iterating over local.service_ports."
  }

  assert {
    condition = output.user_lookup == {
      alice = "ALICE"
      bob   = "BOB"
      john  = "JOHN"
    }
    error_message = "user_lookup must convert the users list into a map keyed by user name."
  }

  assert {
    condition = output.public_service_ports == {
      api = 8080
      web = 8081
    }
    error_message = "public_service_ports must keep only ports below 9000."
  }
}
